### ISSUE TITLE
False ISBN shown

### ISSUE THREAD

**Issue by Raymondcal** [banux/myopds#2]
I have a epub with these two lines in the opf:
```
    <dc:identifier id="BookID" opf:scheme="UUID">5B1399DD-CA70-4B8E-BFE2-21FAE40B194B</dc:identifier>
    <dc:identifier opf:scheme="ISBN">978-2-84344-791-4</dc:identifier>

```
MyOPDS shows "5B1399DD-CA70-4B8E-BFE2-21FAE40B194B" as the ISBN, instead of the real ISBN number.

**Comment by banux** [comment]
This is related to readium2 parsing, it will change if the parser don't use only one identifier.
