### ISSUE TITLE
Search results: only 10 items?

### ISSUE THREAD

**Issue by Raymondcal** [banux/myopds#5]
Does the search results page show only 10 items, even if there are more results possible?

I have all the "Annales de la Compagnie Noire", by Glenn Cook, that is 13 books, and I set every the "Annales de la Compagnie Noire" serie and number manually, in the Edit screen.
But if I search for "compagnie", or "annales" or "cook", the search results page shows only 10 items, not 13.

**Comment by banux** [comment]
Up the limit to 200 results, will be enough for most case.
